### ISSUE TITLE
What should be entered in the Hub URL field ?

### ISSUE THREAD

**Issue by freedomtrain** [peermusic/desktop#55] opened 2016-09-24 16:33 UTC
We are looking to have some of our coop begin using peermusic
At  http://localhost:8000/#/manage-friends/issue what should be entered into the Hub URL field ?

**Comment by perguth** [comment] 2016-09-26 20:02
Duplicate of https://github.com/peermusic/peermusic/issues/53

**Closed as completed by perguth** 2016-09-26 20:02 UTC
