### ISSUE TITLE
How can we set up a signalhub server 

### ISSUE THREAD

**Issue by freedomtrain** [peermusic/desktop#54] opened 2016-09-23 00:44 UTC
Is there documentation on how we can set up a signalhub server for our peermusic instance. 
We want to begin to test with invites and to also understand scaling 

Thanks

**Comment by perguth** [comment] 2016-09-26 20:02
Duplicate of https://github.com/peermusic/peermusic/issues/53

**Closed as completed by perguth** 2016-09-26 20:02 UTC
